# Generated by Django 4.2.5 on 2023-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type_du_produit',
            field=models.CharField(max_length=30),
        ),
    ]
