# Generated by Django 4.2.5 on 2023-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de_comptage', models.FloatField()),
                ('aire_nette', models.FloatField()),
                ('incertitude_aire_nette', models.FloatField()),
                ('taux_de_comptage', models.FloatField(blank=True, null=True)),
                ('incertitude_taux_de_comptage', models.FloatField(blank=True, null=True)),
                ('nom', models.CharField(max_length=15)),
                ('famille', models.CharField(max_length=15)),
                ('masse', models.FloatField(blank=True, null=True)),
                ('activite', models.FloatField(blank=True, null=True)),
                ('incertitude_activite', models.FloatField(blank=True, null=True)),
                ('facteur_de_conversion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
