# Generated by Django 4.2.5 on 2023-09-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de_comptage', models.DateTimeField()),
                ('aire_nette', models.FloatField()),
                ('incertitude_aire_nette', models.FloatField()),
                ('taux_de_comptage', models.FloatField()),
                ('incertitude_taux_de_comptage', models.FloatField()),
                ('nom', models.CharField(max_length=10)),
                ('famille', models.CharField(max_length=10)),
                ('masse', models.FloatField()),
                ('activite', models.FloatField()),
                ('incertitude_activite', models.FloatField()),
                ('facteur_de_conversion', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
