# Generated by Django 4.2.5 on 2023-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruit_de_fond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruitdefond',
            name='temps_de_comptage',
            field=models.FloatField(),
        ),
    ]
